### ISSUE TITLE
pkg-package==0.0.0

### ISSUE THREAD

**Issue by v-smwang** [Ajapaik/ajapaik-web#24]
why can not install pkg-package==0.0.0 for me in  CentOS6.5 ? Can you help me? thanks

**Comment by Lauriy** [comment]
Just skip it?

**Comment by v-smwang** [comment]
sorry，I can not  understand your meaning.
 your meaning is that can run the project normally without installing pkg-package==0.0.0,
 I did not try run it without installing pkg-package==0.0.0.
I am beginner, so I don't know pkg-package of function. Can you tell me ?
You can run the project in ubuntu and install all libs?
Which is operation system and what is software for you develop the project？
Thank you very match！！
