### ISSUE TITLE
search in map view

### ISSUE THREAD

**Issue by puik** [Ajapaik/ajapaik-web#3]
Currently there is no **search functionality in the [map view](https://ajapaik.ee/map/?mapType=OSM&lat=59.43672196916728&lng=24.745684871578305&zoom=18&limitToAlbum=0)**, but when the image density is very high it would be very practical, if a search could be performed only among the images on a current map so that on the map and in the picture panel only images corresponding to the search were kept.

The search box should be in the header.

**Comment by Lauriy** [comment]
https://github.com/Ajapaik/ajapaik-web/blob/master/project/ajapaik/static/js/ajapaik-map.js line 355 we started doing filtering by date. Just for insight into how map filtering could be done.

**Comment by puik** [comment]
@Lauriy, this search should be javascript based doesn't it? No need to query back-end for that? We already have results for map bounding box with descriptions etc so now just filtering it based on the query?

**Comment by Lauriy** [comment]
I guess. Should probably return all translations and some meta fields then?

**Comment by MaertHaekkinen** [comment]
There is map search in Ajapaik-web now.
It was added in with PR #48
