### ISSUE TITLE
user profile page

### ISSUE THREAD

**Issue by puik** [Ajapaik/ajapaik-web#4]
In order to add **more social features** to Ajapaik a **user profile page** is needed:

* User name
* tagline (optional)
* general stats (when joined, how many geotags, rephotos, comments, curated images)
* galleries with images geotagged/curated/dated/commented/favorited by user

**Comment by puik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kasutajaprofiili lehekülg](https://trello.com/c/DtXwfpPI/1507-kasutajaprofiili-lehekulg)

**Comment by github-account-because-they-want-it** [comment]
Idea: use the built-in django [user model](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#user-model) for the username and date_joined and a one-to-one related Profile model for the tagline. the rest of these stats can be collected in the view.

**Comment by MaertHaekkinen** [comment]
User profile page has been added with #38 and improved in #42, #43, #44.
