### ISSUE TITLE
"suggestion has been submitted for this picture" needs proper plural support

### ISSUE THREAD

**Issue by amire80** [Ajapaik/ajapaik-web#54]
There are two strings:
- "1 suggestion has been submitted for this picture. Add yours!"
- "suggestions have been submitted for this picture. Add yours!"

It looks like there are for different quantities. It would be much better to have proper plural support, because not all languages put the number in the beginning of the sentences.

**Comment by MaertHaekkinen** [comment]
It seems that these translations were not actually used by the application, I have since removed any consumption of such translations from the codebase.

**Comment by amire80** [comment]
Thank you!
