### ISSUE TITLE
visual toolbox for editing comments

### ISSUE THREAD

**Issue by puik** [Ajapaik/ajapaik-web#79]
Adding a standard **visual toolbox** for commenting (currently only markup editing possible) to make it easier for users to format their comments, add links, images.

**Comment by MaertHaekkinen** [comment]
The goal of this task is to research and possibly implement a more sophisticated commenting solutions.
Instead of the existing markup-based solution.

The end goal would be to have a commenting system similar to Github/Jira, which supports bold, italic, links, quotes, code(?), etc.

**Comment by MaertHaekkinen** [comment]
Closed in #95
