### ISSUE TITLE
display both title and description

### ISSUE THREAD

**Issue by puik** [Ajapaik/ajapaik-web#86]
Currently in **gallery view** ([see](https://ajapaik.ee/?album=46631)) we display the **beginning of the description** and when opening the picture **only title in shown**.
**We should show both**. And we can have multiple descriptions (different types of descriptions in Muis.ee).

Should we add some separator/identificator for the text as well?
2 lines with line break might look odd. Especially if it happens that the content is nearly identical.

Perhaps one option is also to check if one or the other contains the first one. If there is an exact match, then show the longer one.

**Comment by MaertHaekkinen** [comment]
For displaying the images on the album/images view we use html templates.
The change could possibly be done to either: **frontpage_photo_template.html** or to ***frontpage_async_data*** in ajapaik/ajapaik/views.py

My suggestion is to use a Serializer which makes the `get_display_text` of Photo model accesible
